export const LocalStorageKeys = {
  PENDING_SEND_TO: 'PENDING_SEND_TO',
  ACTIVE_ORDER_ID: 'ACTIVE_ORDER_ID',
  LIST_ORDERS_SELECTED_STORE: 'LIST_ORDERS_SELECTED_STORE',
  SOUND_ENABLED: 'SOUND_ENABLED',
  SELECTED_MENU: 'SELECTED_MENU',
  SELECTED_ITEMS: 'SELECTED_ITEMS',
};
